### ISSUE TITLE
market_data.py error on Python 3.7

### ISSUE THREAD

**Issue by wyczolko** [abhi-g80/pytradesimulator#3]
Excellent project!  I have successfully run 
$ ./server.py
$ ./client.py configs/client1.cfg

However when I try to run 
market_data.py
I get the following error:

U:\pytradesimulator\pytradesim>python market_data.py
2021-05-05 15:22:39.756223 [INFO   ] (main     ) Logging set to info.
2021-05-05 15:22:40.601263 [INFO   ] (onCreate ) Successfully created sessions FIX.4.2:MARKET->MDCLIENT1.
2021-05-05 15:22:41.203971 [INFO   ] (onCreate ) Successfully created sessions FIX.4.2:MARKET->MDCLIENT2.
2021-05-05 15:22:41.284752 [INFO   ] (main     ) FIX.4.2 maarket data server started.
Traceback (most recent call last):
  File "market_data.py", line 73, in <module>
    main()
  File "C:\Users\dwyczolkowski\AppData\Local\Continuum\anaconda3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\dwyczolkowski\AppData\Local\Continuum\anaconda3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\dwyczolkowski\AppData\Local\Continuum\anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\dwyczolkowski\AppData\Local\Continuum\anaconda3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "market_data.py", line 56, in main
    conn = Listener(address, authkey=b"Dj$0.Jkx1@").accept()
  File "C:\Users\dwyczolkowski\AppData\Local\Continuum\anaconda3\lib\multiprocessing\connection.py", line 438, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "C:\Users\dwyczolkowski\AppData\Local\Continuum\anaconda3\lib\multiprocessing\connection.py", line 581, in __init__
    self._socket.bind(address)
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

Any suggestions?

**Comment by abhi-g80** [comment]
Hi, this looks to me like a windows specific issue (as mentioned here).

Could you perhaps try to put the address as "0.0.0.0" and "127.0.0.1" in this [line](https://github.com/abhi-g80/pytradesimulator/blob/master/pytradesim/market_data.py#L42) (replace the string localhost with the mentioned addresses.)
